[tool.poetry]
name = "producthub"
version = "0.1.0"
description = "API for e-commerce product data"
authors = ["Muheez mzscripterx5@gmai.com"]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "*"
uvicorn = "*"
gunicorn = "*"
pandas = "*"
